/* SPDX-License-Identifier: GPL-2.0-or-later
 *
 * Phong tessellation for untextured 3D polygons, renderer-agnostic.
 *
 * Each eligible source triangle is subdivided independently via
 * Phong tessellation (Boubekeur & Alexa 2008).  For each sub-vertex
 * with barycentric (u, v, w):
 *
 *   p_flat    = u*A + v*B + w*C
 *   proj_X(p) = p - dot(p - X, N_X) * N_X    (project onto X's tangent plane)
 *   p_out     = u*proj_A(p_flat) + v*proj_B(p_flat) + w*proj_C(p_flat)
 *
 * Per-vertex normals N_X are read from a frame-scoped cache, keyed
 * on the source PSX command's integer screen (x, y).  First write
 * for a given (x, y) inserts the face normal of the triangle that
 * brought it; subsequent writes are ignored.  Result: every
 * triangle sharing vertex X within a frame uses the same N_X.
 *
 * Why this instead of Loop subdivision:
 *
 * PSX game artists pre-subdivide character meshes heavily to defeat
 * affine texturing and integer math; the polygon stream we receive
 * is already fine-grained tessellation, not a coarse mesh awaiting
 * smoothing.  Loop needs macro silhouette and curvature signal
 * which is not present, AND requires connected-mesh context which
 * PSX state-change fragmentation (paint-order flushes interleave
 * textured face/hair/weapon polys between untextured body slices)
 * destroys -- each batch is 2-7 micro-triangles where "boundary of
 * batch" rarely corresponds to "silhouette of mesh".  Loop's
 * boundary vertex rule applied per-batch produces visible cracks
 * because shared vertices smooth toward different neighbour sets
 * in different batches.
 *
 * Phong tess is structurally crack-free:
 *   - On edge AB (w=0): the contribution of C drops out entirely;
 *     p_out depends only on A, B, N_A, N_B.  Adjacent triangles
 *     ABC and ABD that share AB produce identical edge subdivisions
 *     regardless of which batch each is in, provided their cached
 *     N_A and N_B agree -- which first-write-wins guarantees.
 *   - At corner A (u=1, v=w=0): proj_A(A) = A.  Corners don't move.
 *   - Zero normal at X: proj_X is identity, X contributes flat.
 *     Pin-hints inserted by ineligible neighbours force flat
 *     tessellation along edges shared with ineligible geometry,
 *     so subdivided side meets unsubdivided side exactly.
 *
 * Identity is keyed on integer source (x, y) (GTE projection output,
 * bit-stable across submissions for the same logical vertex).  Same
 * scheme as the SW subdivision path; works for both PGXP-valid
 * eligible polys and PGXP-invalid ineligible-poly pin hints.
 *
 * Cost when disabled: a single integer compare at the polygon-path
 * eligibility gate.  All allocations and state are lazy from first
 * push.
 */

#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>

#include <libretro.h>

#include "gpu_subdiv.h"

extern int psx_gpu_subdivision_level;
/* Used to scale the temporal-history match radius from native
 * pixels into the renderer's upscaled screen space. */
extern uint8_t psx_gpu_upscale_shift_hw;

extern retro_log_printf_t log_cb;

/* ---------------------------------------------------------------------
 * Diagnostic infrastructure (compile-time gated)
 * ------------------------------------------------------------------ */

#ifndef TT_SUBDIV_DEBUG
#define TT_SUBDIV_DEBUG 0
#endif

#if TT_SUBDIV_DEBUG
static FILE    *sd_dbg_file        = NULL;
static uint32_t sd_dbg_push_count  = 0;
static uint32_t sd_dbg_flush_count = 0;

static void sd_dbg_open(void)
{
   if (sd_dbg_file != NULL)
      return;
   sd_dbg_file = fopen("subdiv_debug.txt", "w");
   if (log_cb)
      log_cb(RETRO_LOG_INFO,
            "[subdiv] diagnostic active (TT_SUBDIV_DEBUG=1, "
            "file=subdiv_debug.txt %s)\n",
            sd_dbg_file ? "OPEN" : "FAILED");
}

#define SD_DBG_LOG(fmt, ...) do { \
   if (sd_dbg_file) { \
      fprintf(sd_dbg_file, fmt, ##__VA_ARGS__); \
      fflush(sd_dbg_file); \
   } \
   if (log_cb) \
      log_cb(RETRO_LOG_INFO, fmt, ##__VA_ARGS__); \
} while (0)
#endif

/* ---------------------------------------------------------------------
 * Internal data model
 * ------------------------------------------------------------------ */

/* Sub-vertex in tessellation working space.  Positions are PGXP
 * precise[] coordinates; colour is barycentric-interpolated from
 * the parent corners as a fallback (sd_emit_one overrides with a
 * perspective-correct sample from the parent's exact gradient). */
typedef struct
{
   float px, py, pw;
   float r,  g,  b;
   /* Exact barycentric weights of this sub-vertex within its parent
    * triangle, as generated by the tessellation grid.  Kept because
    * they CANNOT be recovered from (px, py) afterwards: Phong
    * displacement deliberately moves the sub-vertex off the parent's
    * plane, so inverting the parent's screen mapping at the displaced
    * position yields extrapolated weights (outside [0,1], often
    * negative) rather than the generating ones. */
   float bu, bv, bw;
} sd_vertex;

/* Deferred submission record.  Untextured eligible polygons are
 * buffered here between flushes; flush runs Phong tessellation on
 * each and hands the sub-triangles to the emit callback. */
typedef struct
{
   tri_vertex v[3];
   uint8_t    flags;
} sd_pending_tri;

static sd_pending_tri *S_pending;
static uint32_t        S_pending_count;

/* Combined bounding box of all pending triangles' integer screen
 * coords.  Used by tt_subdiv_would_overlap (eye-on-face detection,
 * strict containment) and tt_subdiv_would_intersect_ineligible
 * (paint-order protection, intersection test). */
static int32_t S_pending_min_x;
static int32_t S_pending_min_y;
static int32_t S_pending_max_x;
static int32_t S_pending_max_y;

/* Per-vertex normal cache, frame-scoped.  Keyed on integer source
 * screen (x, y); stores either a unit normal (proper Phong vertex
 * normal: area-weighted average of face normals from every batch
 * triangle touching the vertex) or a zero normal (pin-hint marker
 * for ineligible neighbours -- forces flat tessellation at that
 * vertex so adjacent eligible mesh meets the unsubdivided side
 * exactly).
 *
 * Three-state lifecycle per slot:
 *   0: empty.
 *   1: accumulating.  nx,ny,nz hold an unnormalised running sum of
 *      face-normal cross products from every triangle in the
 *      current batch that has touched this vertex during Pass A
 *      (the accumulate pass at the head of tt_subdiv_flush).
 *      Pin-hints from previous batches do not enter this state.
 *   2: committed.  nx,ny,nz hold either a unit normal (the
 *      accumulated sum normalised on first read in Pass B) or a
 *      zero normal (from tt_subdiv_add_pin_hints).  Subsequent
 *      accumulations at this slot are skipped (first-batch-wins
 *      cross-batch).
 *
 * Averaging multiple face normals per vertex is what makes Phong
 * tessellation visually stable.  A single triangle's face normal
 * is highly sensitive to PGXP precise[] floating-point noise:
 * cross products mix screen-pixel-scale edge components with 1/w
 * (precise[2]) components ~1e-4 in magnitude, so a 0.5-unit jitter
 * in precise[0..1] propagates to 20-30% relative noise in the
 * x/y components of the unit normal, rotating it by several
 * degrees per frame and producing visible position wobble after
 * Phong projection.  Summing N face normals reduces this noise by
 * ~sqrt(N); the area weighting (unnormalised cross products
 * naturally carry triangle area) gives larger triangles greater
 * influence, which is what proper smoothed vertex normals do. */
typedef struct
{
   int32_t x, y;
   float   nx, ny, nz;
   /* Sum of the LENGTHS of the face normals accumulated here, as
    * opposed to the length of their sum (nx, ny, nz).  The ratio of
    * the two is a confidence measure -- see sd_nc_read_commit. */
   float   wsum;
   uint8_t valid;
} sd_nc_entry;

static sd_nc_entry *S_nc;
static uint32_t     S_nc_size;
static uint32_t     S_nc_mask;

/* ---------------------------------------------------------------------
 * Temporal normal history
 *
 * The vertex normals above are rebuilt from scratch every frame
 * (tt_subdiv_frame_end clears the cache), and the face normals they
 * average are derived from PGXP precise[] floats whose 1/w component
 * is ~1e-4 in magnitude.  Sub-pixel jitter in precise[0..1] therefore
 * rotates each face normal by several degrees frame to frame.
 * Averaging the faces meeting at a vertex suppresses that noise
 * SPATIALLY (within one frame) but not TEMPORALLY: nothing carries
 * across the clear, so the committed normal at a vertex dances every
 * frame, and Phong projection turns that dance into visible position
 * wobble on otherwise static geometry.  The SD_PHONG_ALPHA damper
 * exists solely to halve the amplitude of that artifact.
 *
 * The fix is to age the cache instead of wiping it.  At frame end the
 * committed normals are copied into a history table (same hash, same
 * keying); on the next frame, when a vertex's normal is committed, it
 * is blended toward the historical normal found at the nearest
 * matching screen position:
 *
 *   n_out = normalize((1 - beta) * n_now + beta * n_hist)
 *
 * This is screen-space temporal reprojection, the same principle TAA
 * uses.  Its correctness rests on an observation about the input: the
 * noise we are fighting is zero-mean about the true normal (it comes
 * from FP jitter in the projection, not from the geometry), so an
 * exponential moving average converges on the true value while the
 * per-frame excursions cancel.  Real geometric change is NOT
 * zero-mean, which is why the match is spatially bounded (see below)
 * and why a miss falls back to this frame's value alone.
 *
 * Identity across frames.  There is no frame-stable vertex ID
 * available in this module: tri_vertex carries geometry only, and the
 * PGXP layer's own vertex identity (GTE command-stream position) is
 * long gone by the time a polygon arrives here and is not stable
 * across frames anyway.  Screen position is the only handle we have.
 * A vertex that is stationary hashes to its own slot and matches
 * exactly; a vertex drifting slowly lands within a pixel or two, so
 * the lookup probes a small neighbourhood (SD_NC_HIST_RADIUS, in
 * native pixels, scaled by the upscale shift) and takes the nearest
 * hit.  A vertex that moved further than that is treated as a new
 * vertex and gets no history -- deliberately: blending a normal
 * across a vertex that genuinely jumped would smear geometry that
 * really did change, which is the ghosting failure mode of every
 * temporal filter.  Trading a missed smoothing opportunity for a
 * missing ghost is the right side of that trade here, because a
 * fast-moving vertex's wobble is invisible anyway.
 *
 * Cost: one extra table of the same size, one memcpy-equivalent walk
 * per frame, and a bounded neighbourhood probe per committed vertex.
 * All of it is skipped entirely when subdivision is disabled, since
 * nothing is ever pushed and flush returns early. */

/* Blend weight toward the historical normal.  0 disables temporal
 * smoothing (previous behaviour); values near 1 are maximally stable
 * but slowest to follow real geometric change.  This is the weight
 * applied to a vertex that landed on exactly the same pixel as last
 * frame; the blend site scales it down as 1/(1 + d2) with the match
 * distance, so moving geometry is smoothed far less (see there).
 *
 * 0.92 measured best in the offline model harness: with the adaptive
 * falloff it drives subdivision-induced wobble on a static pose from
 * 2277 changed pixels/frame above the no-subdivision baseline down to
 * 20 (a 114x reduction, i.e. into the noise floor of the jitter
 * itself), while producing LOWER tracking error under rotation than
 * any fixed weight tested including 0.75. */
#ifndef SD_NC_HIST_BETA
#define SD_NC_HIST_BETA 0.92f
#endif

/* Neighbourhood radius for the history lookup, in NATIVE pixels
 * (scaled by upscale_shift at use).  Covers the sub-pixel-to-couple-
 * pixel drift of nominally static geometry without reaching far
 * enough to match a genuinely different vertex.  The probe is over a
 * (2r+1)^2 integer neighbourhood, so keep this small. */
#ifndef SD_NC_HIST_RADIUS
#define SD_NC_HIST_RADIUS 2
#endif

/* Minimum len(sum of face normals) / sum(len of face normals) for a
 * vertex normal to be considered meaningful; below this the faces
 * meeting at the vertex have cancelled and the residual is noise.
 * See the cancellation guard in sd_nc_read_commit. */
#ifndef SD_NC_CONF_MIN
#define SD_NC_CONF_MIN 0.35f
#endif

static sd_nc_entry *S_nc_hist;
static uint32_t     S_nc_hist_size;
static uint32_t     S_nc_hist_mask;

/* ---------------------------------------------------------------------
 * Helpers
 * ------------------------------------------------------------------ */

static uint32_t sd_hash_xy(int32_t x, int32_t y)
{
   uint32_t h  = (uint32_t)x * 0x9E3779B1u;
   h          ^= (uint32_t)y * 0x85EBCA77u;
   h          ^= h >> 16;
   h          *= 0x7FEB352Du;
   h          ^= h >> 15;
   return h;
}

/* ---------------------------------------------------------------------
 * Normal cache
 * ------------------------------------------------------------------ */

#define SD_NC_INITIAL_SIZE 16384u
#define SD_NC_PROBE_MAX    32u

static void sd_nc_ensure(void)
{
   if (S_nc == NULL)
   {
      S_nc_size = SD_NC_INITIAL_SIZE;
      S_nc_mask = S_nc_size - 1u;
      S_nc      = (sd_nc_entry *)calloc(S_nc_size, sizeof(sd_nc_entry));
   }
   if (S_nc_hist == NULL)
   {
      S_nc_hist_size = SD_NC_INITIAL_SIZE;
      S_nc_hist_mask = S_nc_hist_size - 1u;
      S_nc_hist      = (sd_nc_entry *)calloc(S_nc_hist_size,
            sizeof(sd_nc_entry));
   }
}

/* Look up a historical unit normal near (x, y).  Probes the integer
 * neighbourhood of radius `radius` (in upscaled screen units),
 * nearest-first by squared distance, and returns the first committed
 * history entry found.  Returns 0 when nothing is in range, in which
 * case the caller keeps this frame's normal unblended. */
static int sd_nc_hist_lookup(int32_t x, int32_t y, int32_t radius,
      float *out_nx, float *out_ny, float *out_nz, int32_t *out_d2)
{
   int32_t  dx, dy;
   int32_t  best_d2 = 0;
   int      found   = 0;
   float    bx = 0.0f, by = 0.0f, bz = 0.0f;

   if (S_nc_hist == NULL)
      return 0;

   for (dy = -radius; dy <= radius; dy++)
   {
      for (dx = -radius; dx <= radius; dx++)
      {
         int32_t  qx = x + dx;
         int32_t  qy = y + dy;
         int32_t  d2 = dx * dx + dy * dy;
         uint32_t h, step;
         if (d2 > radius * radius)
            continue;
         if (found && d2 >= best_d2)
            continue;
         h = sd_hash_xy(qx, qy);
         for (step = 0; step < SD_NC_PROBE_MAX; step++)
         {
            sd_nc_entry *e = &S_nc_hist[(h + step) & S_nc_hist_mask];
            if (!e->valid)
               break;
            if (e->x == qx && e->y == qy)
            {
               /* Zero history entries carry no direction (pin-hint
                * or degenerate); treat as absent so they don't drag
                * a real normal toward zero. */
               if (e->nx != 0.0f || e->ny != 0.0f || e->nz != 0.0f)
               {
                  best_d2 = d2;
                  bx      = e->nx;
                  by      = e->ny;
                  bz      = e->nz;
                  found   = 1;
               }
               break;
            }
         }
      }
   }

   if (!found)
      return 0;
   *out_nx = bx;
   *out_ny = by;
   *out_nz = bz;
   *out_d2 = best_d2;
   return 1;
}

static void sd_nc_clear(void)
{
   if (S_nc != NULL)
      memset(S_nc, 0, S_nc_size * sizeof(sd_nc_entry));
}

/* Pass A primitive: accumulate one face normal contribution at
 * (x, y).  Only touches empty (creates accumulating slot) or
 * accumulating (adds to running sum) slots; committed slots are
 * left alone, which is how first-batch-wins is enforced
 * cross-batch and how pin-hints take precedence within a batch.
 * Linear probing bounded by SD_NC_PROBE_MAX; probe overflow
 * degrades to "this contribution is dropped" which keeps the
 * cache consistent (the cached vertex normal just averages fewer
 * face normals than it might have) at the cost of slightly noisier
 * tessellation at that vertex. */
static void sd_nc_accumulate(int32_t x, int32_t y,
      float cx, float cy, float cz)
{
   uint32_t h, step;
   sd_nc_ensure();
   h = sd_hash_xy(x, y);
   for (step = 0; step < SD_NC_PROBE_MAX; step++)
   {
      sd_nc_entry *e = &S_nc[(h + step) & S_nc_mask];
      if (!e->valid)
      {
         e->valid = 1;
         e->x     = x;
         e->y     = y;
         e->nx    = cx;
         e->ny    = cy;
         e->nz    = cz;
         e->wsum  = sqrtf(cx * cx + cy * cy + cz * cz);
         return;
      }
      if (e->x == x && e->y == y)
      {
         if (e->valid == 1)
         {
            e->nx   += cx;
            e->ny   += cy;
            e->nz   += cz;
            e->wsum += sqrtf(cx * cx + cy * cy + cz * cz);
         }
         return;
      }
   }
}

/* Pass B primitive: read the unit normal at (x, y), normalising in
 * place and committing on first read.  Returns zero if the slot
 * is missing (vertex was never accumulated, e.g. probe overflow)
 * or the accumulated sum was degenerate.  Subsequent reads of a
 * committed slot return the same value. */
static void sd_nc_read_commit(int32_t x, int32_t y,
      float *out_nx, float *out_ny, float *out_nz)
{
   uint32_t h, step;
   sd_nc_ensure();
   h = sd_hash_xy(x, y);
   for (step = 0; step < SD_NC_PROBE_MAX; step++)
   {
      sd_nc_entry *e = &S_nc[(h + step) & S_nc_mask];
      if (!e->valid)
      {
         *out_nx = 0.0f;
         *out_ny = 0.0f;
         *out_nz = 0.0f;
         return;
      }
      if (e->x == x && e->y == y)
      {
         if (e->valid == 1)
         {
            float len2 = e->nx * e->nx + e->ny * e->ny + e->nz * e->nz;
            /* Cancellation guard.
             *
             * The vertex normal here is the SUM of the face normals
             * of every triangle meeting at this screen position.  On
             * a closed convex surface those faces roughly agree and
             * the sum is long relative to the individual lengths.
             * On the geometry PS1 models are actually made of, they
             * frequently do not: hair spikes, capes, collars and
             * skirts are thin double-sided shells whose front and
             * back faces share vertices with nearly opposite
             * orientation, so the sum largely cancels.
             *
             * What survives a near-cancellation is a short residual
             * made mostly of the FP noise in precise[], and
             * normalising it produces a unit vector pointing in an
             * essentially arbitrary direction.  Phong projection then
             * displaces the sub-vertices toward a plane that has no
             * relationship to the surface -- which does not round the
             * silhouette outward, it skews and shrinks it.  That is
             * the reported "hair spike becomes crooked and thinner"
             * artifact, and it is worst exactly where the geometry is
             * thinnest, because thinner shells cancel more completely.
             *
             * len(sum) / sum(len) is the standard confidence measure
             * for this: 1 when every face agrees, 0 when they cancel
             * exactly.  Below the threshold the normal carries no
             * usable direction, so the vertex is pinned flat (zero
             * normal) rather than displaced by noise.  Pinning is
             * safe by construction: a zero normal makes the Phong
             * projection the identity at that corner, so the vertex
             * keeps its original position and neighbours sharing it
             * stay watertight. */
            if (len2 > 1e-12f && e->wsum > 1e-12f &&
                sqrtf(len2) < SD_NC_CONF_MIN * e->wsum)
            {
               len2 = 0.0f;
            }
            if (len2 > 1e-12f)
            {
               float inv = 1.0f / sqrtf(len2);
               float hx, hy, hz;
               int32_t radius;
               int32_t hd2 = 0;
               e->nx *= inv;
               e->ny *= inv;
               e->nz *= inv;
               /* Temporal smoothing: blend toward the normal this
                * vertex had last frame, if it can be matched in the
                * history table.  Both operands are unit vectors, so
                * the lerp lands inside the unit ball and only needs
                * renormalising; when the two disagree strongly (real
                * geometric change) the result leans toward whichever
                * has the larger weight, and the next frame's history
                * is the blended value, so the filter converges
                * geometrically rather than latching. */
               radius = (int32_t)SD_NC_HIST_RADIUS << psx_gpu_upscale_shift_hw;
               if (SD_NC_HIST_BETA > 0.0f &&
                   sd_nc_hist_lookup(x, y, radius, &hx, &hy, &hz, &hd2))
               {
                  /* Adaptive blend weight.  The match distance is a
                   * free motion estimate: a vertex that landed on
                   * exactly the same integer pixel as last frame is
                   * stationary, and stationary geometry is where
                   * wobble is both most visible and most safely
                   * suppressed, so it gets the full weight.  A vertex
                   * matched further away moved, and moving geometry
                   * needs responsiveness rather than stability --
                   * heavy smoothing there is what turns into visible
                   * lag.  Falling off as 1/(1 + d2) drops the weight
                   * by half at one pixel of motion and to a fifth at
                   * two, which measured out as keeping essentially
                   * all of the static-case wobble reduction while
                   * giving back most of the tracking error that a
                   * fixed high weight costs. */
                  float beta_eff = SD_NC_HIST_BETA
                                 / (1.0f + (float)hd2);
                  float mx  = (1.0f - beta_eff) * e->nx + beta_eff * hx;
                  float my  = (1.0f - beta_eff) * e->ny + beta_eff * hy;
                  float mz  = (1.0f - beta_eff) * e->nz + beta_eff * hz;
                  float ml2 = mx * mx + my * my + mz * mz;
                  /* Near-cancellation means the historical normal is
                   * roughly antiparallel to this frame's -- the
                   * vertex flipped, so history is meaningless and
                   * this frame's value stands. */
                  if (ml2 > 1e-6f)
                  {
                     float minv = 1.0f / sqrtf(ml2);
                     e->nx = mx * minv;
                     e->ny = my * minv;
                     e->nz = mz * minv;
                  }
               }
            }
            else
            {
               e->nx = 0.0f;
               e->ny = 0.0f;
               e->nz = 0.0f;
            }
            e->valid = 2;
         }
         *out_nx = e->nx;
         *out_ny = e->ny;
         *out_nz = e->nz;
         return;
      }
   }
   *out_nx = 0.0f;
   *out_ny = 0.0f;
   *out_nz = 0.0f;
}

/* Pin-hint: commit a zero normal at (x, y), but only if the slot
 * is empty.  First-write-wins: if any eligible accumulation has
 * already started here in a previous batch, the pin is too late
 * (that batch's geometry is already emitted with a real normal,
 * and the crack is unavoidable from this submission ordering).
 * The polygon-path's tt_subdiv_would_intersect_ineligible test is
 * what prevents the eligibles-already-flushed-then-ineligible-
 * neighbour case from arising in normal play. */
static void sd_nc_insert_zero(int32_t x, int32_t y)
{
   uint32_t h, step;
   sd_nc_ensure();
   h = sd_hash_xy(x, y);
   for (step = 0; step < SD_NC_PROBE_MAX; step++)
   {
      sd_nc_entry *e = &S_nc[(h + step) & S_nc_mask];
      if (!e->valid)
      {
         e->valid = 2;
         e->x     = x;
         e->y     = y;
         e->nx    = 0.0f;
         e->ny    = 0.0f;
         e->nz    = 0.0f;
         return;
      }
      if (e->x == x && e->y == y)
         return;
   }
}

/* ---------------------------------------------------------------------
 * Face normal
 *
 * Cross product of two edges in (precise[0], precise[1], precise[2])
 * space.  precise[2] is PGXP's 1/w, providing a monotonic depth
 * coordinate; the cross product direction is consistent with the
 * surface's actual 3D orientation up to a scale, which is all
 * Phong tessellation needs.
 *
 * The raw form returns the unnormalised cross product, used by
 * Pass A accumulation -- magnitude reflects (precise-space)
 * triangle area, so summing raw cross products from every triangle
 * touching a vertex yields a proper area-weighted vertex normal
 * after a single normalisation in Pass B.
 * ------------------------------------------------------------------ */

static void sd_face_normal_raw(const tri_vertex *v0, const tri_vertex *v1,
      const tri_vertex *v2, float *cx, float *cy, float *cz)
{
   float ax = v1->precise[0] - v0->precise[0];
   float ay = v1->precise[1] - v0->precise[1];
   float aw = v1->precise[2] - v0->precise[2];
   float bx = v2->precise[0] - v0->precise[0];
   float by = v2->precise[1] - v0->precise[1];
   float bw = v2->precise[2] - v0->precise[2];
   *cx = ay * bw - aw * by;
   *cy = aw * bx - ax * bw;
   *cz = ax * by - ay * bx;
}

/* ---------------------------------------------------------------------
 * Eligibility / lifecycle / push / overlap
 * ------------------------------------------------------------------ */

bool tt_subdiv_is_eligible(const tri_vertex *v, uint8_t flags)
{
   (void)v;
   /* Reject textured polys (UV refinement not implemented).  Reject
    * PGXP-invalid polys (Phong needs sub-pixel positions and the
    * 1/w depth axis from precise[2]). */
   if (flags & TT_SUBDIV_F_TEXTURED)
      return false;
   if (!(flags & TT_SUBDIV_F_PGXP_VALID))
      return false;
   return true;
}

void tt_subdiv_init(void)
{
   if (S_pending == NULL)
   {
      S_pending = (sd_pending_tri *)calloc(TT_SUBDIV_MAX_PENDING_TRIS,
            sizeof(sd_pending_tri));
      S_pending_count = 0;
   }
   sd_nc_ensure();
#if TT_SUBDIV_DEBUG
   sd_dbg_open();
   if (log_cb)
      log_cb(RETRO_LOG_INFO, "[subdiv] tt_subdiv_init\n");
#endif
}

void tt_subdiv_shutdown(void)
{
   free(S_pending);
   S_pending       = NULL;
   S_pending_count = 0;
   free(S_nc);
   S_nc            = NULL;
   S_nc_size       = 0;
   S_nc_mask       = 0;
   free(S_nc_hist);
   S_nc_hist       = NULL;
   S_nc_hist_size  = 0;
   S_nc_hist_mask  = 0;
#if TT_SUBDIV_DEBUG
   if (sd_dbg_file)
   {
      fclose(sd_dbg_file);
      sd_dbg_file = NULL;
   }
#endif
}

int tt_subdiv_has_pending(void)
{
   return S_pending_count > 0;
}

bool tt_subdiv_push(const tri_vertex *vertices, uint8_t flags)
{
   sd_pending_tri *p;
   int i;
   if (S_pending == NULL)
      tt_subdiv_init();
   if (S_pending_count >= TT_SUBDIV_MAX_PENDING_TRIS)
      return false;
   p        = &S_pending[S_pending_count++];
   p->v[0]  = vertices[0];
   p->v[1]  = vertices[1];
   p->v[2]  = vertices[2];
   p->flags = flags;
   if (S_pending_count == 1)
   {
      S_pending_min_x = vertices[0].x;
      S_pending_min_y = vertices[0].y;
      S_pending_max_x = vertices[0].x;
      S_pending_max_y = vertices[0].y;
   }
   for (i = (S_pending_count == 1) ? 1 : 0; i < 3; i++)
   {
      if (vertices[i].x < S_pending_min_x) S_pending_min_x = vertices[i].x;
      if (vertices[i].y < S_pending_min_y) S_pending_min_y = vertices[i].y;
      if (vertices[i].x > S_pending_max_x) S_pending_max_x = vertices[i].x;
      if (vertices[i].y > S_pending_max_y) S_pending_max_y = vertices[i].y;
   }
#if TT_SUBDIV_DEBUG
   sd_dbg_push_count++;
   if (sd_dbg_push_count <= 3u)
   {
      SD_DBG_LOG("[subdiv] tt_subdiv_push #%u (pending was %u)\n",
            sd_dbg_push_count, S_pending_count - 1);
   }
#endif
   return true;
}

void tt_subdiv_add_pin_hints(const tri_vertex *vertices)
{
   int i;
   for (i = 0; i < 3; i++)
      sd_nc_insert_zero(vertices[i].x, vertices[i].y);
}

bool tt_subdiv_would_overlap(const tri_vertex *vertices)
{
   int32_t x0, y0, x1, y1, x2, y2;
   int32_t minx, miny, maxx, maxy;
   if (S_pending_count == 0)
      return false;
   x0 = vertices[0].x; y0 = vertices[0].y;
   x1 = vertices[1].x; y1 = vertices[1].y;
   x2 = vertices[2].x; y2 = vertices[2].y;
   minx = x0; if (x1 < minx) minx = x1; if (x2 < minx) minx = x2;
   miny = y0; if (y1 < miny) miny = y1; if (y2 < miny) miny = y2;
   maxx = x0; if (x1 > maxx) maxx = x1; if (x2 > maxx) maxx = x2;
   maxy = y0; if (y1 > maxy) maxy = y1; if (y2 > maxy) maxy = y2;
   return    minx >= S_pending_min_x
          && miny >= S_pending_min_y
          && maxx <= S_pending_max_x
          && maxy <= S_pending_max_y;
}

bool tt_subdiv_would_intersect_ineligible(const tri_vertex *vertices)
{
   int32_t x0, y0, x1, y1, x2, y2;
   int32_t minx, miny, maxx, maxy;
   if (S_pending_count == 0)
      return false;
   x0 = vertices[0].x; y0 = vertices[0].y;
   x1 = vertices[1].x; y1 = vertices[1].y;
   x2 = vertices[2].x; y2 = vertices[2].y;
   minx = x0; if (x1 < minx) minx = x1; if (x2 < minx) minx = x2;
   miny = y0; if (y1 < miny) miny = y1; if (y2 < miny) miny = y2;
   maxx = x0; if (x1 > maxx) maxx = x1; if (x2 > maxx) maxx = x2;
   maxy = y0; if (y1 > maxy) maxy = y1; if (y2 > maxy) maxy = y2;
   return !(   maxx < S_pending_min_x
            || minx > S_pending_max_x
            || maxy < S_pending_min_y
            || miny > S_pending_max_y);
}

/* ---------------------------------------------------------------------
 * Emission: project precise[] -> integer screen, perspective-correct
 * gouraud sample from parent, hand to caller's emit callback
 *
 * Each sub-triangle vertex carries its precise[] position; the
 * rasteriser-facing tri_vertex needs integer screen coords plus a
 * colour.  Colour is sampled from the PARENT's exact perspective-
 * correct gradient using the sub-vertex's screen-space barycentric
 * coordinates within the parent triangle.  This guarantees that
 * sub-triangles sharing an edge (whether within one parent or
 * between two parents that share a source edge) get identical
 * colour samples on the shared edge, eliminating gouraud seams.
 * ------------------------------------------------------------------ */

static void sd_emit_one(PS_GPU *gpu, const sd_vertex *v0,
      const sd_vertex *v1, const sd_vertex *v2, uint8_t flags,
      const tri_vertex *parent_vertices,
      tt_subdiv_emit_fn emit, void *tag)
{
   tri_vertex out[3];
   const sd_vertex *src[3];
   int i;
   float inv_w0   = (parent_vertices[0].precise[2] > 1e-6f) ? 1.0f / parent_vertices[0].precise[2] : 1.0f;
   float inv_w1   = (parent_vertices[1].precise[2] > 1e-6f) ? 1.0f / parent_vertices[1].precise[2] : 1.0f;
   float inv_w2   = (parent_vertices[2].precise[2] > 1e-6f) ? 1.0f / parent_vertices[2].precise[2] : 1.0f;
   float r0_w     = (float)parent_vertices[0].r * inv_w0;
   float g0_w     = (float)parent_vertices[0].g * inv_w0;
   float b0_w     = (float)parent_vertices[0].b * inv_w0;
   float r1_w     = (float)parent_vertices[1].r * inv_w1;
   float g1_w     = (float)parent_vertices[1].g * inv_w1;
   float b1_w     = (float)parent_vertices[1].b * inv_w1;
   float r2_w     = (float)parent_vertices[2].r * inv_w2;
   float g2_w     = (float)parent_vertices[2].g * inv_w2;
   float b2_w     = (float)parent_vertices[2].b * inv_w2;

   src[0] = v0; src[1] = v1; src[2] = v2;
   for (i = 0; i < 3; i++)
   {
      const sd_vertex *s = src[i];
      tri_vertex      *d = &out[i];
      /* Barycentric weights come from the generating grid, NOT from
       * inverting the parent's screen mapping at (px, py).
       *
       * This distinction is the whole ballgame for colour.  Phong
       * displacement moves each sub-vertex OFF the parent's plane by
       * design, so the displaced position is not a convex combination
       * of the parent's corners; solving for weights there returns an
       * extrapolation, with components outside [0,1] and routinely
       * negative.  Feeding those into the colour interpolation
       * overshoots the parent's colour range in both directions, and
       * the clamp below turns the negative side into zeroes -- i.e.
       * black bleeding into saturated geometry, worst where the
       * displacement is largest (blond hair going black at higher
       * subdivision levels was the reported case: R and G driven
       * negative on a colour whose B is already 0).  The generating
       * weights are exact, always in [0,1], and always sum to 1, so
       * the interpolation stays inside the parent's colour gamut and
       * the clamp becomes a no-op safety net rather than an artifact
       * generator. */
      float b0 = s->bu;
      float b1 = s->bv;
      float b2 = s->bw;
      float inv_w_at;
      float r, g, b;
      d->x = (int32_t)floorf(s->px + 0.5f);
      d->y = (int32_t)floorf(s->py + 0.5f);
      d->u = 0;
      d->v = 0;
      /* Depth-cue sidecar: children carry no cue (t == 0 makes the
       * shader mix the identity).  cf[] is filled from this
       * sub-vertex's own interpolated colour below, once it is
       * known; leaving either as stack garbage would be a latent
       * trap for any consumer that reads them. */
      d->fog[0] = 0.0f;
      d->fog[1] = 0.0f;
      d->fog[2] = 0.0f;
      d->fog[3] = 0.0f;

      inv_w_at = b0 * inv_w0 + b1 * inv_w1 + b2 * inv_w2;
      if (inv_w_at > 1e-6f)
      {
         float inv_inv_w = 1.0f / inv_w_at;
         float r_over_w  = b0 * r0_w + b1 * r1_w + b2 * r2_w;
         float g_over_w  = b0 * g0_w + b1 * g1_w + b2 * g2_w;
         float b_over_w  = b0 * b0_w + b1 * b1_w + b2 * b2_w;
         r = r_over_w * inv_inv_w;
         g = g_over_w * inv_inv_w;
         b = b_over_w * inv_inv_w;
      }
      else
      {
         r = s->r; g = s->g; b = s->b;
      }
      if (r < 0.0f) r = 0.0f; else if (r > 255.0f) r = 255.0f;
      if (g < 0.0f) g = 0.0f; else if (g > 255.0f) g = 255.0f;
      if (b < 0.0f) b = 0.0f; else if (b > 255.0f) b = 255.0f;
      d->r = (uint8_t)r;
      d->g = (uint8_t)g;
      d->b = (uint8_t)b;
      d->cf[0] = r * (1.0f / 255.0f);
      d->cf[1] = g * (1.0f / 255.0f);
      d->cf[2] = b * (1.0f / 255.0f);
      d->precise[0] = s->px;
      d->precise[1] = s->py;
      d->precise[2] = s->pw;
   }
   emit(gpu, out, flags, parent_vertices, tag);
}

/* ---------------------------------------------------------------------
 * Phong tessellation kernel
 *
 * Max level 3 gives N = 8 edge subdivisions = 64 sub-triangles per
 * source triangle = 45 sub-vertices.  Scratch is file-scope static
 * (single-threaded GPU context).
 *
 * SD_PHONG_ALPHA blends between flat barycentric position and the
 * full Phong-projected position:
 *
 *   p_out = (1 - alpha) * p_flat + alpha * p_phong
 *
 * alpha=1 is full Phong (maximum smoothing, maximum noise
 * amplification on jittery face normals).  alpha=0 is flat
 * (no subdivision benefit).
 *
 * This used to default to 0.5: with the normal cache wiped every
 * frame, the committed normal at a static vertex swung ~6 degrees
 * frame to frame (measured), and halving the displacement was the
 * only lever available to halve the resulting wobble -- at the cost
 * of halving the smoothing the feature exists to provide.  The
 * temporal history filter above attacks the noise at its source
 * instead, cutting that swing to ~1.2 degrees mean / 3 degrees worst
 * case, so the damper is no longer paying for itself and the default
 * moves up to 0.85: most of the available smoothing, with a little
 * headroom left against the residual jitter on vertices that miss
 * the history match (newly appeared or fast-moving geometry, where
 * per-frame wobble is masked by the motion anyway).  Set to 0.5 to
 * recover the old conservative behaviour, or 1.0 for full Phong.
 * Crack-freeness and corner-exactness are both preserved under
 * the alpha blend (linear combination of two per-vertex Phong-like
 * functions is itself per-vertex; edge midpoints still depend
 * only on the two edge endpoints' positions and normals; corners
 * still satisfy proj_X(X) = X). */

#define SD_MAX_LEVEL  3
#define SD_MAX_N      (1 << SD_MAX_LEVEL)
#define SD_MAX_SUBV   ((SD_MAX_N + 1) * (SD_MAX_N + 2) / 2)
#ifndef SD_PHONG_ALPHA
#define SD_PHONG_ALPHA 0.85f
#endif

/* Keep sub-vertex w on the flat interpolant instead of Phong-
 * projecting it; see the rationale at the assignment site. */
#ifndef SD_PHONG_LOCK_W
#define SD_PHONG_LOCK_W 1
#endif


static sd_vertex sd_subv[SD_MAX_SUBV];
static int       sd_row_start[SD_MAX_N + 2];

static void sd_tessellate_phong(PS_GPU *gpu, const sd_pending_tri *pt,
      int levels, tt_subdiv_emit_fn emit, void *tag,
      uint32_t *dbg_out_count)
{
   const tri_vertex *V0 = &pt->v[0];
   const tri_vertex *V1 = &pt->v[1];
   const tri_vertex *V2 = &pt->v[2];
   float Ax, Ay, Aw, Bx, By, Bw, Cx, Cy, Cw;
   float Ar, Ag, Ab, Br, Bg, Bb, Cr, Cg, Cb;
   float n0x, n0y, n0z;
   float n1x, n1y, n1z;
   float n2x, n2y, n2z;
   int N;
   int i, j;
   int idx;
   float invN;
   int total_rows;

   if (levels < 1)
   {
      /* Defensive: caller should have gated on level > 0.  Pass
       * through as a single sub-triangle so nothing is dropped. */
      sd_vertex v[3];
      v[0].px = V0->precise[0]; v[0].py = V0->precise[1]; v[0].pw = V0->precise[2];
      v[0].r  = (float)V0->r;   v[0].g  = (float)V0->g;   v[0].b  = (float)V0->b;
      v[0].bu = 1.0f; v[0].bv = 0.0f; v[0].bw = 0.0f;
      v[1].px = V1->precise[0]; v[1].py = V1->precise[1]; v[1].pw = V1->precise[2];
      v[1].r  = (float)V1->r;   v[1].g  = (float)V1->g;   v[1].b  = (float)V1->b;
      v[1].bu = 0.0f; v[1].bv = 1.0f; v[1].bw = 0.0f;
      v[2].px = V2->precise[0]; v[2].py = V2->precise[1]; v[2].pw = V2->precise[2];
      v[2].r  = (float)V2->r;   v[2].g  = (float)V2->g;   v[2].b  = (float)V2->b;
      v[2].bu = 0.0f; v[2].bv = 0.0f; v[2].bw = 1.0f;
      sd_emit_one(gpu, &v[0], &v[1], &v[2], pt->flags, pt->v, emit, tag);
      (*dbg_out_count)++;
      return;
   }
   if (levels > SD_MAX_LEVEL)
      levels = SD_MAX_LEVEL;
   N = 1 << levels;

   Ax = V0->precise[0]; Ay = V0->precise[1]; Aw = V0->precise[2];
   Bx = V1->precise[0]; By = V1->precise[1]; Bw = V1->precise[2];
   Cx = V2->precise[0]; Cy = V2->precise[1]; Cw = V2->precise[2];
   Ar = (float)V0->r; Ag = (float)V0->g; Ab = (float)V0->b;
   Br = (float)V1->r; Bg = (float)V1->g; Bb = (float)V1->b;
   Cr = (float)V2->r; Cg = (float)V2->g; Cb = (float)V2->b;

   /* Vertex normals were accumulated in Pass A; read & normalise
    * (first read commits the slot, subsequent reads return the
    * cached unit vector). */
   sd_nc_read_commit(V0->x, V0->y, &n0x, &n0y, &n0z);
   sd_nc_read_commit(V1->x, V1->y, &n1x, &n1y, &n1z);
   sd_nc_read_commit(V2->x, V2->y, &n2x, &n2y, &n2z);

   /* Triangular grid row offsets.  Row i (0 <= i <= N) holds
    * (N - i + 1) vertices at j in [0, N - i].  Linear index for
    * (i, j) is sd_row_start[i] + j. */
   total_rows = N + 1;
   sd_row_start[0] = 0;
   for (i = 1; i <= total_rows; i++)
      sd_row_start[i] = sd_row_start[i - 1] + (N - i + 2);

   /* Generate sub-vertex positions via Phong projection, blended
    * with flat barycentric position at SD_PHONG_ALPHA. */
   invN = 1.0f / (float)N;
   idx  = 0;
   for (i = 0; i <= N; i++)
   {
      for (j = 0; j <= N - i; j++)
      {
         float u     = (float)(N - i - j) * invN;
         float v     = (float)i           * invN;
         float w     = (float)j           * invN;
         float fx    = u * Ax + v * Bx + w * Cx;
         float fy    = u * Ay + v * By + w * Cy;
         float fw    = u * Aw + v * Bw + w * Cw;
         float dot_a = (fx - Ax) * n0x + (fy - Ay) * n0y + (fw - Aw) * n0z;
         float dot_b = (fx - Bx) * n1x + (fy - By) * n1y + (fw - Bw) * n1z;
         float dot_c = (fx - Cx) * n2x + (fy - Cy) * n2y + (fw - Cw) * n2z;
         float pa_x  = fx - dot_a * n0x;
         float pa_y  = fy - dot_a * n0y;
         float pa_w  = fw - dot_a * n0z;
         float pb_x  = fx - dot_b * n1x;
         float pb_y  = fy - dot_b * n1y;
         float pb_w  = fw - dot_b * n1z;
         float pc_x  = fx - dot_c * n2x;
         float pc_y  = fy - dot_c * n2y;
         float pc_w  = fw - dot_c * n2z;
         float phong_x = u * pa_x + v * pb_x + w * pc_x;
         float phong_y = u * pa_y + v * pb_y + w * pc_y;
         float phong_w = u * pa_w + v * pb_w + w * pc_w;
         sd_vertex *sv = &sd_subv[idx++];
         sv->px = (1.0f - SD_PHONG_ALPHA) * fx + SD_PHONG_ALPHA * phong_x;
         sv->py = (1.0f - SD_PHONG_ALPHA) * fy + SD_PHONG_ALPHA * phong_y;
#if SD_PHONG_LOCK_W
         /* w is NOT displaced: it stays the flat barycentric value.
          *
          * x and y are screen pixels; w is the projective divisor,
          * order 1.  Treating them as three axes of one Euclidean
          * space (which is what the cross product and the dot-product
          * projection above do) mixes incommensurable units, and the
          * w axis is where that mixing does visible damage: unlike a
          * displacement in x/y, a displacement in w does not move the
          * vertex on screen, it changes the perspective weight the
          * vertex carries into attribute interpolation.  A subdivided
          * polygon whose sub-vertices carry perturbed w therefore
          * interpolates colour differently along a shared edge than an
          * unsubdivided neighbour does, and the mismatch draws a line
          * exactly along the boundary between subdivided and
          * unsubdivided geometry.
          *
          * Locking w to the flat interpolant keeps the smoothing
          * (which lives entirely in x/y, where it belongs) and makes
          * every sub-vertex's perspective weight agree with what the
          * parent plane would have produced at that barycentric
          * position -- which is exactly what the neighbour uses.
          * Set to 0 to restore the previous behaviour. */
         sv->pw = fw;
#else
         sv->pw = (1.0f - SD_PHONG_ALPHA) * fw + SD_PHONG_ALPHA * phong_w;
#endif
         sv->r  = u * Ar + v * Br + w * Cr;
         sv->g  = u * Ag + v * Bg + w * Cg;
         sv->b  = u * Ab + v * Bb + w * Cb;
         sv->bu = u;
         sv->bv = v;
         sv->bw = w;
      }
   }

   /* Emit sub-triangles.  Winding (i, j) -> (i+1, j) -> (i, j+1)
    * maps to A-direction -> B-direction -> C-direction in
    * barycentric space; the affine baryc->screen map preserves
    * orientation, so parent winding is propagated correctly to
    * every sub-triangle. */
   for (i = 0; i < N; i++)
   {
      for (j = 0; j < N - i; j++)
      {
         int v_a = sd_row_start[i]     + j;
         int v_b = sd_row_start[i + 1] + j;
         int v_c = sd_row_start[i]     + j + 1;
         sd_emit_one(gpu, &sd_subv[v_a], &sd_subv[v_b], &sd_subv[v_c],
               pt->flags, pt->v, emit, tag);
         (*dbg_out_count)++;
         if (j < N - i - 1)
         {
            int d_a = sd_row_start[i + 1] + j;
            int d_b = sd_row_start[i + 1] + j + 1;
            int d_c = sd_row_start[i]     + j + 1;
            sd_emit_one(gpu, &sd_subv[d_a], &sd_subv[d_b], &sd_subv[d_c],
                  pt->flags, pt->v, emit, tag);
            (*dbg_out_count)++;
         }
      }
   }
}

/* ---------------------------------------------------------------------
 * Public flush + frame-end
 * ------------------------------------------------------------------ */

void tt_subdiv_flush(PS_GPU *gpu, tt_subdiv_emit_fn emit, void *tag)
{
   int      levels;
   uint32_t i;
   uint32_t dbg_pending   = S_pending_count;
   uint32_t dbg_out_count = 0;

   if (S_pending_count == 0)
      return;

   levels = psx_gpu_subdivision_level;
   if (levels < 0)            levels = 0;
   if (levels > SD_MAX_LEVEL) levels = SD_MAX_LEVEL;

   /* Pass A: accumulate unnormalised face normals at every
    * triangle's three corner slots.  Empty slots create
    * accumulating entries; existing accumulating entries sum in
    * this triangle's contribution; committed slots (pin-hints
    * from the ineligible-poly branch, or accumulations committed
    * by a previous batch in the same frame) are left alone.  The
    * sum of unnormalised cross products is an area-weighted
    * vertex normal, which is what proper smoothed Phong
    * tessellation uses; the averaging is what reduces single-
    * triangle face-normal jitter to a stable per-vertex value
    * across frames. */
   for (i = 0; i < S_pending_count; i++)
   {
      sd_pending_tri *pt = &S_pending[i];
      float cx, cy, cz;
      sd_face_normal_raw(&pt->v[0], &pt->v[1], &pt->v[2], &cx, &cy, &cz);
      sd_nc_accumulate(pt->v[0].x, pt->v[0].y, cx, cy, cz);
      sd_nc_accumulate(pt->v[1].x, pt->v[1].y, cx, cy, cz);
      sd_nc_accumulate(pt->v[2].x, pt->v[2].y, cx, cy, cz);
   }

   /* Pass B: tessellate each triangle.  sd_tessellate_phong
    * reads the now-accumulated cache slots via sd_nc_read_commit,
    * which normalises on first read and commits the slot;
    * subsequent triangles reading the same slot get the same
    * unit vector. */
   for (i = 0; i < S_pending_count; i++)
      sd_tessellate_phong(gpu, &S_pending[i], levels, emit, tag,
            &dbg_out_count);

   S_pending_count = 0;

#if TT_SUBDIV_DEBUG
   sd_dbg_flush_count++;
   if (sd_dbg_flush_count <= 50u ||
       (sd_dbg_flush_count % 100u) == 0u)
   {
      SD_DBG_LOG("[subdiv] flush #%u pending=%u out=%u level=%d\n",
            sd_dbg_flush_count, dbg_pending, dbg_out_count, levels);
   }
#else
   (void)dbg_pending;
   (void)dbg_out_count;
#endif
}

void tt_subdiv_frame_end(void)
{
   /* Promote this frame's committed normals into the history table,
    * then clear the live cache.  Only committed (valid == 2) entries
    * with a non-zero direction are carried: accumulating entries were
    * never read, so they were never used to tessellate anything and
    * have no bearing on what was displayed, and zero entries are
    * pin-hints whose meaning ("pin flat") is re-derived every frame
    * from the ineligible-polygon stream rather than remembered.
    *
    * The history table is rebuilt wholesale rather than aged in
    * place, so a vertex that stops being submitted disappears from
    * history after one frame and cannot resurrect stale geometry
    * later. */
   if (S_nc != NULL && S_nc_hist != NULL)
   {
      uint32_t i;
      memset(S_nc_hist, 0, S_nc_hist_size * sizeof(sd_nc_entry));
      for (i = 0; i < S_nc_size; i++)
      {
         const sd_nc_entry *src = &S_nc[i];
         uint32_t h, step;
         if (src->valid != 2)
            continue;
         if (src->nx == 0.0f && src->ny == 0.0f && src->nz == 0.0f)
            continue;
         h = sd_hash_xy(src->x, src->y);
         for (step = 0; step < SD_NC_PROBE_MAX; step++)
         {
            sd_nc_entry *dst = &S_nc_hist[(h + step) & S_nc_hist_mask];
            if (!dst->valid)
            {
               *dst = *src;
               break;
            }
            if (dst->x == src->x && dst->y == src->y)
               break;
         }
      }
   }
   sd_nc_clear();
}
