
#include "mednafen/psx/irq.cpp"
#include "mednafen/psx/timer.cpp"
#include "mednafen/psx/frontio.cpp"
#include "mednafen/psx/cpu.cpp"
#include "mednafen/psx/gte.cpp"
#include "mednafen/psx/dis.cpp"
#include "mednafen/psx/cdc.cpp"
#include "mednafen/psx/spu.cpp"
#include "mednafen/psx/gpu.cpp"
#include "mednafen/psx/mdec.cpp"
#include "mednafen/psx/input/gamepad.cpp"
#include "mednafen/psx/input/dualanalog.cpp"
#include "mednafen/psx/input/dualshock.cpp"
#include "mednafen/psx/input/justifier.cpp"
#include "mednafen/psx/input/guncon.cpp"
#include "mednafen/psx/input/negcon.cpp"
#include "mednafen/psx/input/memcard.cpp"
#include "mednafen/psx/input/multitap.cpp"
#include "mednafen/psx/input/mouse.cpp"

#include "mednafen/error.cpp"
#include "mednafen/settings.cpp"
#include "mednafen/general.cpp"
#include "mednafen/FileStream.cpp"
#include "mednafen/MemoryStream.cpp"
#include "mednafen/Stream.cpp"
#include "mednafen/state.cpp"

#ifdef NEED_CD
#include "mednafen/cdrom/CDAccess.cpp"
#include "mednafen/cdrom/CDAccess_Image.cpp"
#include "mednafen/cdrom/CDAccess_CCD.cpp"
#include "mednafen/cdrom/SimpleFIFO.cpp"
#include "mednafen/cdrom/audioreader.cpp"
#include "mednafen/cdrom/cdromif.cpp"
#include "mednafen/cdrom/misc.cpp"
#endif

#include "mednafen/mempatcher.cpp"
#include "mednafen/video/Deinterlacer.cpp"
#include "mednafen/video/surface.cpp"

#include "libretro.cpp"
